name: microgo
description: A lightweight and efficient implementation of the Go-based programming language optimised to run on 8-bit Microchip microcontrollers.
homepage: https://github.com/tiagohm/microgo
version: 0.1.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  equatable: ^1.2.0
  meta: ^1.2.0
  antlr4: ^4.8.0-dev.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
